[[plugins]]
package = "netlify-plugin-a11y"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]
  
  # required config
  checkPaths = ['/']
  
  # optional config
  # ignoreDirectories = ['/admin']  # explicitly ignore these directories
  resultMode = "warn" # is "error" by default

  # Developer only
  # debugMode = true # extra logging for plugin developers